# Generated by Django 5.2.7 on 2025-10-08 16:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('secretary', 'Secrétaire de Crédit'), ('officer', 'Officier de Crédit'), ('manager', 'Responsable de Crédit')], default='secretary', max_length=20)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom_off_groupe', models.CharField(max_length=100)),
                ('prenom_off_groupe', models.CharField(max_length=100)),
                ('succursale', models.CharField(choices=[('aeroport2', 'Aeroport2'), ('direction_generale', 'Direction Général SogeCarte'), ('cap_haitien', 'Cap Haïtien'), ('cayes', 'Cayes'), ('conseil_administration', 'Conseil d administration SogeCarte'), ('frere', 'Frère'), ('lalue', 'Lalue'), ('petion_ville_iv', 'Pétion-ville IV'), ('petion_ville_3', 'Pétion-ville 3'), ('rue_pavee', 'Rue Pavée'), ('turgeau', 'Turgeau'), ('autres', 'Autres')], max_length=50)),
                ('no_succursale', models.CharField(max_length=20)),
                ('autre_succursale', models.CharField(blank=True, max_length=100)),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('cin', models.CharField(max_length=50, verbose_name='CIN/NIF/Passeport')),
                ('adresse_client', models.TextField(blank=True)),
                ('telephone_client', models.CharField(blank=True, max_length=20)),
                ('email_client', models.EmailField(blank=True, max_length=254)),
                ('type_dossier', models.CharField(choices=[('pre_approuve', 'Pre-Approuvé'), ('vente_croisee', 'Vente-croisée'), ('campagne', 'Campagne')], max_length=20)),
                ('type_campagne', models.CharField(blank=True, max_length=100)),
                ('date_debut_campagne', models.DateField(blank=True, null=True)),
                ('date_fin_campagne', models.DateField(blank=True, null=True)),
                ('type_carte_application', models.CharField(choices=[('credit', 'Carte de crédit'), ('sogephone', 'SogePhone'), ('tele_haiti', 'Télé Haïti'), ('digicel', 'Digicel'), ('american', 'American')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('montant_genere', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('type_carte_final', models.CharField(blank=True, choices=[('master_gold', 'MASTER CARD GOLD'), ('master_gold_aa', 'MASTER CARD GOLD AA'), ('master_intl', "MASTER CARD INT'L"), ('master_local', 'MASTER CARD LOCAL'), ('master_black', 'MASTER CARD BLACK'), ('visa_business', 'VISA BUSINESS'), ('visa_gold', 'VISA GOLD'), ('visa_intl', "VISA INT'L"), ('visa_local', 'VISA LOCAL'), ('visa_platinum', 'VISA PLATINUM')], max_length=20)),
                ('raison', models.CharField(blank=True, choices=[('gage_demande', 'GAGE DEMANDE'), ('application_signee', 'APPLICATION SIGNEE'), ('client_introuvable', 'CLIENT INTROUVABLE'), ('employeur_impossible', 'EMPLOYEUR IMPOSSIBLE A TROUVER'), ('pieces_manquante', 'PIECES MANQUANTE')], max_length=30)),
                ('limite_credit_approuve', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_decision', models.DateField(blank=True, null=True)),
                ('commentaire_traitement', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL)),
                ('officer_credit', models.ForeignKey(limit_choices_to={'role': 'officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.creditapplication')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.creditapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
