# Generated by Django 5.2.7 on 2026-01-05 17:41

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_creditapplication_officer_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='application_id',
            field=models.CharField(default=authentication.models.generate_application_id, editable=False, max_length=32, unique=True),
        ),
    ]
