# Generated by Django 5.2.7 on 2026-01-07 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_creditapplication_application_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('create_app', 'Création Dossier'), ('update_app', 'Modification Dossier'), ('delete_app', 'Suppression Dossier'), ('assign_officer', 'Assignation Officier'), ('generate_report', 'Génération Rapport'), ('export_data', 'Export Données'), ('create_user', 'Création Utilisateur'), ('update_user', 'Modification Utilisateur'), ('delete_user', 'Suppression Utilisateur')], max_length=20)),
                ('resource_type', models.CharField(blank=True, help_text='Type de ressource (CreditApplication, User, Report, etc)', max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID de la ressource affectée', max_length=100)),
                ('resource_display', models.CharField(blank=True, help_text='Affichage lisible de la ressource', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Détails des changements en JSON')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failed', 'Échoué')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur en cas d'échec")),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='authenticat_user_id_3b88ca_idx'), models.Index(fields=['action', 'timestamp'], name='authenticat_action_4a725a_idx'), models.Index(fields=['timestamp'], name='authenticat_timesta_ba49b1_idx')],
            },
        ),
    ]
